trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'src/QuickPlot.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# required for NUnit to work with .NET Core
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestStable'
    
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# MSTest on any project with tests
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# NUnit tests for .NET Core project
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'src/QuickPlot.Tests.Integration/QuickPlot.Tests.Integration.csproj'
    arguments: '--configuration $(buildConfiguration)'

# NUnit tests for .NET Core project
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'src/QuickPlot.Tests.Unit/QuickPlot.Tests.Unit.csproj'
    arguments: '--configuration $(buildConfiguration)'
